### ISSUE TITLE
[Some different answer]

### ISSUE THREAD

**Issue by plChao** [marmot0814/Compiler-2019-Fall-testcase#3]
# A little bit not sure
## marmot0814Test2.p
>line 15 的 function call type 沒有 match，是我多檢查嗎?
## iamch15542binarytest.p
不一樣在 output 132-135
> sample answer
```+=132
<Error> Found in line 72, column 19: invalid operands to binary operation '/' ('integer' and 'string')
        print 1.1 + 5 / "ccccaaa" * 4;
                      ^
<Error> Found in line 73, column 19: invalid operands to binary operation '*' ('integer' and 'string')
        print 1.1 + 5 * "bbbbb" / 4 - oct();
                      ^
```
> myanswer
```
<Error> Found in line 72, column 31: invalid operands to binary operation '*' ('string' and 'integer')
        print 1.1 + 5 / "ccccaaa" * 4;
                                  ^
<Error> Found in line 73, column 19: invalid operands to binary operation '*' ('real' and 'string')
        print 1.1 + 5 * "bbbbb" / 4 - oct();
                      ^
```
>我猜測是 parser 的 operator 優先度差別所造成的(?
跟據 hw2 優先度應該是
![image](https://user-images.githubusercontent.com/32629259/71542220-80298e00-299e-11ea-992b-a2d9136ad4d5.png)
# unsure
## iamch15542sometest.p
>line 20 的 over subscribe 不知道可不可以跳過，我認為數量跟 child 沒關係，所以還是有檢查(?

**Comment by marmot0814** [comment]
Hi, 你好
> ## marmot0814Test2.p
> > line 15 的 function call type 沒有 match，是我多檢查嗎?

這段寫在spec的Type Coercion部份
> ### Type Coercion and Comparison
> 
> - An integer type can be implicit converted into a real type due to several situations, such as assignments, parameter passing, or arithmetic expressions.

line 15 是一個int傳進去real參數, 所以是合法的

> ## iamch15542binarytest.p
> 不一樣在 output 132-135
> 
> > sample answer
> 
> ```
> <Error> Found in line 72, column 19: invalid operands to binary operation '/' ('integer' and 'string')
>         print 1.1 + 5 / "ccccaaa" * 4;
>                       ^
> <Error> Found in line 73, column 19: invalid operands to binary operation '*' ('integer' and 'string')
>         print 1.1 + 5 * "bbbbb" / 4 - oct();
>                       ^
> ```
> 
> > myanswer
> 
> ```
> <Error> Found in line 72, column 31: invalid operands to binary operation '*' ('string' and 'integer')
>         print 1.1 + 5 / "ccccaaa" * 4;
>                                   ^
> <Error> Found in line 73, column 19: invalid operands to binary operation '*' ('real' and 'string')
>         print 1.1 + 5 * "bbbbb" / 4 - oct();
>                       ^
> ```
> 
> > 我猜測是 parser 的 operator 優先度差別所造成的(?
> > 跟據 hw2 優先度應該是
> > ![image](https://user-images.githubusercontent.com/32629259/71542220-80298e00-299e-11ea-992b-a2d9136ad4d5.png)

expression的順序我沒有按照hw2 spec來做, 因為有點不合常理。
不過我有在[issue #101](https://github.com/compiler-f19/Discussion/issues/101)提到這個問題, 助教也說expression的測資都會用括號括起來, 所以順序不會影響。

> # unsure
> ## iamch15542sometest.p
> > line 20 的 over subscribe 不知道可不可以跳過，我認為數量跟 child 沒關係，所以還是有檢查(?

看完覺得有點道理, 因為數量跟child沒關係。
不過曾經助教發過[這個回覆](https://github.com/compiler-f19/Discussion/issues/108#issuecomment-569108405)
> 停下來指的都是「同一個節點」可能會有多個語意錯誤要檢查，那中間有其中一個有誤就跳開。除了 program node 頭尾都要檢查外。

按照spec中的敘述
> ### Variable Declaration and Reference
> 
> - In an array declaration, the index of the lower bound must be smaller than that of the upper bound. Both of the indices must be greater than or equal to zero; actually, a non-conforming input was already blocked according to the syntactic definition.
> 
> - If there is an error in the array declaration, further checking is unnecessary when visiting the Variable Reference Node which is a reference to that array.
> 
> - **Each index of an array reference must be of the integer type. Further checking regarding the array reference is unnecessary if an incorrect index was found within the array reference.** The order of index checking is from left to right. Bound checking is not performed at compile time as in C language.
> 
> - An over array subscript is not allowed, that is, the number of indices of an array reference cannot be greater than the number of dimensions in the declaration.

spec中有提到如果有個index爛掉, 後面跟array reference相關的檢查不必要。

所以我們這部份實做都選擇遇到問題就跳離node的概念來寫, 不過我覺得這有討論空間, 萬一有爭議的話可以跟助教反應。
